//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace delivery.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class deliveryEntities1 : DbContext
    {
        public deliveryEntities1()
            : base("name=deliveryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataHuman> DataHuman { get; set; }
        public virtual DbSet<DataPersonal> DataPersonal { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<MenuRis> MenuRis { get; set; }
        public virtual DbSet<MenuRoll> MenuRoll { get; set; }
        public virtual DbSet<MenuSushi> MenuSushi { get; set; }
        public virtual DbSet<MenuWok> MenuWok { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<payments> payments { get; set; }
        public virtual DbSet<promotion> promotion { get; set; }
        public virtual DbSet<reviews> reviews { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vacancy> vacancy { get; set; }
    }
}
